constant_force_norm: 10
dataset:
  real_data: True
  max_traj_length: 500
  sensor_subsample: 50
models:
  rep_learning_model:
    name: ReconstructionModel
    force_size: 90
    locations_size: 6
    representation_size: 1024
    gru_tbptt_step_size:
    input_num_random_samples: 128
    reconstruction_num_random_samples: 128
    pe_max_freq_log2: 4
    force_predictor_hidden: 2048
    decoder_input_embed_dim: 1020
    gru_input_embed_dim: 252
    consistency_reg_weight: 0.0
    mask_percentage: 0.2
    trajectory_level_mask: True
    dropout: 0
  downstream_model:
    name: TransposedConvImagePred
    num_channels: 8
    num_bins: 3
    dropout: 0
    balance_image_classes: False